service:
  address:
    ip: ""
    port: 4431
  tls:
    generate_if_missing: true
    certificate:
      raw: ""
      path: cert.pem
    key:
      raw: ""
      path: key.pem
  http1_address:
    ip: ""
    port: 4430
  http1_address_tls:
    ip: ""
    port: 4431
