service:
  address:
    ip: ""
    port: 443
  tls:
    generate_if_missing: true
    certificate:
      raw: ""
      path: cert.pem
    key:
      raw: ""
      path: key.pem
  http1_address:
    ip: ""
    port: 443
