service:
  http:
    h3: 
      address:
        ip: ""
        port: 4431
    h1:
      address:
        ip: ""
        port: 4431
    h1_ssl:
      address:
        ip: ""
        port: 4430
  tls:
    generate_if_missing: true
    certificate:
      raw: ""
      path: cert.pem
    key:
      raw: ""
      path: key.pem
  mcp:
    enabled: true
    address:
      ip: ""
      port: 4432
