docs_dir: pages
site_name: ashttp3lib

nav:
  - 'Home': 'index.md'
  - 'Guides':
    - 'Getting started': 'gettingstarted.md'
    - 'Primer': 'primer.md'
    - 'Cookbook': 'cookbook.md'
    - 'Glossary': 'glossary.md'
  - 'Advanced':
    - 'Compiling': 'compiling.md'
    - 'Internals': 'internals.md'
    - 'Specification': 'spec.md'
    - 'Roadmap': 'roadmap.md'
  - 'Contributing': 'contributing.md'
  - 'Reference': 'reference.md'
  - 'Versions': 'versions.md'

theme: material

markdown_extensions:
  - toc:
      permalink: False
      baselevel: 2
      toc_depth: 5
  - admonition
  - attr_list
  - codehilite
  - pymdownx.magiclink

copyright: "Copyright &copy; 2024 Ayush Anand"

extra_css:
  - 'extra.css'

repo_name: 'ayushanand18/as-http3lib'
repo_url: 'https://github.com/ayushanand18/as-http3lib'