name: Go Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download Go modules
        run: go mod download

      - name: Install OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Run setup script (generate certs, configure sysctl)
        run: |
          chmod +x ./setup.sh
          sudo ./setup.sh

      - name: Run all tests
        run: go test -v ./...
